version: '3'

services:
  backend_service:
    build: .
    ports:
      - "8000:8000"
  
  mysql_service:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: vikesh
      MYSQL_DATABASE: flask_timbbadb